app/pizzas/routes.py
from flask import Blueprint, render_template, request, redirect, url_for

import constants
from app import db
from app.db_models import Pizzas, Toppings

bp = Blueprint('pizzas', __name__, template_folder='templates')
toppingsDict = []


@bp.route('/', methods=constants.http_verbs)
def view_pizzas():
    if request.method == 'GET':
        pizzas = Pizzas.query.all()
        toppings = Toppings.query.all()
        # loop through db toppings value and deduct the amount in the toppings json
        if len(toppingsDict) > 0:
            for i in range(0, len(toppingsDict)):
                for j in range(0, len(toppings)):
                    if int(toppingsDict[i]['toppingId']) == toppings[j].id:
                        toppings[j].topping_qty = toppings[j].topping_qty - 1
        return render_template('pizzas_list.html', len=len(pizzas), pizzas=pizzas, toppings=toppings,
                               toppings_len=len(toppings), toppingsDict=toppingsDict,
                               toppingsDictLen=len(toppingsDict), title='Pizza Manager')


@bp.route('/add-topping/<topping_id>', methods=constants.http_verbs)
def new_pizza_toppings(topping_id):
    if request.method == 'PUT':
        topping = db.session.query(Toppings).filter_by(id=topping_id).first()
        toppingsDict.append({'toppingId': topping_id, 'toppingName': topping.topping_name})
        return "Successful Addition"


@bp.route('/remove-topping/<array_index>', methods=constants.http_verbs)
def remove_pizza_topping(array_index):
    if request.method == 'PUT':
        toppingsDict.pop(int(array_index))
        return "Successful Removal"


@bp.route('/add-pizza', methods=constants.http_verbs)
def save_pizza():
    if request.method == 'POST':
        pizza_name = request.form.get("pizza-name")
        new_pizza = Pizzas(pizza_name=pizza_name, pizza_toppings=toppingsDict)
        try:
            db.session.add(new_pizza)
            db.session.commit()
            # loop through toppings on the new pizza and update the toppings table
            for i in range(0, len(toppingsDict)):
                topping = db.session.query(Toppings).filter_by(id=toppingsDict[i]['toppingId']).first()
                topping.topping_qty = topping.topping_qty - 1
                db.session.commit()
            toppingsDict.clear()
        except Exception as ex:
            db.session.rollback()
            return render_template("500.html", error=str(ex))
        return redirect(url_for('pizzas.view_pizzas'))


@bp.route('/delete-pizza/<pizza_id>', methods=constants.http_verbs)
def delete_pizza(pizza_id):
    if request.method == 'DELETE':
        pizza = db.session.query(Pizzas).filter_by(id=pizza_id).first()
        db.session.delete(pizza)
        db.session.commit()
        return "Deletion of pizza successful."

app/pizzas/templates/edit_pizza.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- jQuery CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<body>
<h1>Pizza List Manager</h1>

<nav>
    <a class="nav-link" href="{{ url_for('pizza-toppings.view_pizza_toppings') }}">Pizza Toppings Manager</a>
    <a class="nav-link" href="{{ url_for('pizzas.view_pizzas') }}">Pizza List Manager</a>
</nav>

<p>You are editing the following pizza</p>

<form method="post" action="{{ url_for('edit-pizza.update_pizza', pizza_id=pizza.id) }}">
    <label for="pizza-name">Pizza Name:</label>
    <input type="text" id="pizza-name" name="pizza-name" placeholder="{{pizza.pizza_name}}"
           value="{{pizza.pizza_name}}"/>
    <button class="add-new-pizza" type="submit">Update Pizza</button>
</form>

<p>Current Pizza Toppings:</p>
<div id="pizza-toppings-div">
    <ol>
        {% for i in range(0, current_toppings_len) %}
        <li>{{pizza.pizza_toppings[i].toppingName}}</li>
        <button class="remove-topping-button"
                onclick="removeOriginalToppingFromPizza({{pizza.id}}, {{pizza.pizza_toppings[i].toppingId}})">
            Remove Topping
        </button>
        {% endfor %}
    </ol>
</div>

<p>Updated Pizza Toppings:</p>
<div id="updated-pizza-toppings-div">
    <ol>
        <p>Added Toppings:</p>
        {% for i in range(0, updated_toppings_len) %}
        <li>{{updated_toppings[i].toppingName}}</li>
        <button class="remove-topping-button" onclick="removingNewToppingFromPizza({{[i]}})">
            Remove New Topping
        </button>
        {% endfor %}
    </ol>
</div>

<p>Toppings Available To Add:</p>
<ol>
    {% for i in range(0, available_toppings_len) %}
    <li class="toppings-list">{{available_toppings[i].topping_name}} - {{available_toppings[i].topping_qty}}
        {% if available_toppings[i].topping_qty > 0 %}
        <span class="toppings-qty">
            <button class="add-topping-to-pizza-btn"
                    onclick="addToppingTPizza({{available_toppings[i].id}})">Add Topping</button>
        </span>
        {% endif %}
    </li>
    {% endfor %}
</ol>
<script type="text/javascript">
    function addToppingTPizza(toppingId) {
        $.ajax({
            url: "/edit-pizza/add-topping/" + toppingId,
            type: "PUT",
            success: function (data, status) {
                location.href = "{{url_for('edit-pizza.edit_pizza', pizza_id=current_pizza_id)}}";
            }
        });
    }

    function removeOriginalToppingFromPizza(pizzaId, toppingId, toppingInfo) {
        $.ajax({
            url: "/edit-pizza/remove-original-topping?pizzaId=" + pizzaId + "&toppingId=" + toppingId,
            type: "PUT",
            success: function (data, status) {
                location.href = "{{url_for('edit-pizza.edit_pizza', pizza_id=current_pizza_id)}}";
            }
        });
    }

    function removingNewToppingFromPizza(arrayIndex) {
        $.ajax({
            url: "/edit-pizza/remove-new-topping/" + arrayIndex,
            type: "PUT",
            success: function (data, status) {
                location.href = "{{url_for('edit-pizza.edit_pizza', pizza_id=current_pizza_id)}}";
            }
        });
    }
</script>
</body>
</html>

app/pizzas/templates/pizzas_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- jQuery CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</head>
<body>
<h1>Pizza List Manager</h1>

<nav>
    <a class="nav-link" href="{{ url_for('pizza-toppings.view_pizza_toppings') }}">Pizza Toppings Manager</a>
    <a class="nav-link" href="{{ url_for('pizzas.view_pizzas') }}">Pizza List Manager</a>
</nav>

<p>Below is your current list of pizzas:</p>
<ol>
    {% for i in range(0, len) %}
    <li>{{pizzas[i].pizza_name}}</li>
    <span class="update-pizza">
        <a class="update-pizza-btn"
                href="{{ url_for('edit-pizza.edit_pizza', pizza_id=pizzas[i].id) }}">Edit Pizza</a>
    </span>
    <span class="delete-pizza">
        <button class="delete-pizza-btn"
                onclick="deletePizza({{pizzas[i].id}})">Delete Pizza</button>
    </span>
    {% endfor %}
</ol>

<h3>Add New Pizza Form</h3>
<form method="post" action="{{ url_for('pizzas.save_pizza') }}">
    <label for="pizza-name">Pizza Name:</label>
    <input type="text" id="pizza-name" name="pizza-name" placeholder="Pizza Name"/>
    {% if toppingsDictLen > 0 %}
    <button class="add-new-pizza" type="submit">Add New Pizza</button>
    {% endif %}
</form>

<ol>
    {% for i in range(0, toppings_len) %}
    <li class="toppings-list">{{toppings[i].topping_name}} - {{toppings[i].topping_qty}}
        {% if toppings[i].topping_qty > 0 %}
        <span class="toppings-qty">
            <button class="add-topping-to-pizza-btn"
                    onclick="addToppingToNewPizza({{toppings[i].id}})">Add Topping</button>
        </span>
        {% endif %}
    </li>
    {% endfor %}
</ol>

{% if toppingsDictLen > 0 %}
<div id="new-pizza-toppings-div">
    <h4>Currently Selected Toppings</h4>
    <ol>
        {% for i in range(0, toppingsDictLen) %}
        <li>{{toppingsDict[i].toppingName}}</li>
        <button class="delete-topping-button" onclick="removingToppingFromPizza({{[i]}})">
            Remove Topping
        </button>
        {% endfor %}
    </ol>
</div>
{% endif %}

<script type="text/javascript">
    function addToppingToNewPizza(toppingId) {
        $.ajax({
            url: "/pizzas/add-topping/" + toppingId,
            type: "PUT",
            success: function (data, status) {
                location.href = "{{url_for('pizzas.view_pizzas')}}";
            }
        });
    }

    function removingToppingFromPizza(arrayIndex) {
        $.ajax({
            url: "/pizzas/remove-topping/" + arrayIndex,
            type: "PUT",
            success: function (data, status) {
                location.href = "{{url_for('pizzas.view_pizzas')}}";
            }
        });
    }

    function deletePizza(pizzasId) {
        $.ajax({
            url: "/pizzas/delete-pizza/" + pizzasId,
            type: "DELETE",
            success: function (data, success) {
                location.href = "{{url_for('pizzas.view_pizzas')}}";
            }
        });
    }
</script>
</body>
</html>